fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    # Ne pas oublier de remplacer AppBundle par App ! :) :) :) :)
    from_email:
        address: super.chess.online@gmail.com
        sender_name: Chess Online
        
    profile:
        form:
            type: App\Form\ProfileFormType
    
    #registration:
        #confirmation:
            #enabled: true
            #template: '@FOSUser/Registration/email.txt.twig'
        
